name: Extract init_boot/boot image

on:
    workflow_dispatch:
        inputs:
            fileurl:
                description: 'link of full OxygenOS/ColorOS file'
                required: true
                type: string

env:
    GH_TOKEN: ${{ github.token }}

jobs:
    extracting-boot:
        runs-on: ubuntu-latest
        outputs:
          id: ota-link
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            
            - name: Set up Environment
              run: |
                sudo apt-get update
                sudo apt-get install -y aria2
            
            - name: Downloading otadump    
              run: wget -O otadump https://github.com/crazystylus/otadump/releases/download/0.1.2/otadump-0.1.2-x86_64-unknown-linux-gnu.tar.gz && tar xvf otadump && rm LICENSE README.md
            
            - name: Downloading OTA
              run: aria2c -x16 -s16 -o ota.zip --user-agent='Dalvik/2.1.0 (Linux; V; Android 15; PKR110 Build/AQ3A.240617.008)' "${{ github.event.inputs.fileurl }}"
            
            - name: Extracting zip 
              run: unzip ota.zip 
                
            - name: Setting up Release name
              run: |  
                echo "REL_NAME=$(grep "version_name=" META-INF/com/android/metadata | sed 's/^[^=]*=//')" >> $GITHUB_ENV
                echo "############## $(echo ${{env.REL_NAME}}) ##############"
            
            - name: Dumping boot and init_boot    
              run: | 
                cd OOS*/ && cd OOS*/
                cp ./boot.img ./init_boot.img $GITHUB_WORKSPACE
                sha1sum boot.img > boot.img.sha1sum
                sha1sum init_boot.img > init_boot.img.sha1sum
            
            - name: Creating release
              run: |
                gh release create $REL_NAME --title $(echo $REL_NAME) --notes "" boot.img init_boot.img boot.img.sha1sum init_boot.img.sha1sum
